using System.Globalization;

namespace SubscriptionTracker.Application.Localization;

public static class LocalizationCatalog
{
    private static readonly IReadOnlyDictionary<string, string> Ru = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["DashboardNav"] = "Панель управления",
        ["SubscriptionsNav"] = "Подписки",
        ["CalendarNav"] = "Календарь платежей",
        ["AnalyticsNav"] = "Аналитика",
        ["HistoryNav"] = "История платежей",
        ["SettingsNav"] = "Настройки",
        ["MainSubtitle"] = "Персональный контроль подписок",
        ["HeaderBadgeText"] = "Локально · SQLite · Без облака",
        ["SidebarStatusTitle"] = "Локальный режим",
        ["SidebarStatusDetails"] = "База: SQLite",
        ["LastRefreshTodayFormat"] = "Последнее обновление: сегодня, {0:HH:mm}",
        ["LastRefreshDateFormat"] = "Последнее обновление: {0:dd.MM.yyyy HH:mm}",
        ["ThemeDark"] = "Темная",
        ["ThemeLight"] = "Светлая",
        ["StorageMode"] = "SQLite, локально на устройстве",
        ["BackupStatus"] = "Резервные копии позволяют сохранить и восстановить локальную базу.",
        ["AppVersion"] = ".NET 8 · MVP build",
        ["NoComment"] = "Без комментария",
        ["NoUpcomingPayments"] = "Нет ближайших списаний",
        ["AddFirstSubscription"] = "Добавьте первую подписку",
        ["EmptyState"] = "Пусто",
        ["PerMonthSuffix"] = "{0}/мес",
        ["NotCounted"] = "Не учитывается",
        ["StatusActive"] = "Активна",
        ["StatusInactive"] = "Отключена",
        ["CountdownOverdue"] = "Просрочено на {0} дн.",
        ["CountdownToday"] = "Сегодня",
        ["CountdownInOneDay"] = "Через 1 день",
        ["CountdownInFewDays"] = "Через {0} дня",
        ["CountdownInManyDays"] = "Через {0} дней",
        ["UrgencyOverdue"] = "Просрочен",
        ["UrgencyToday"] = "Сегодня",
        ["UrgencySoon"] = "Скоро",
        ["UrgencyThisWeek"] = "На неделе",
        ["UrgencyPlanned"] = "Запланирован",
        ["MostExpensiveFallback"] = "—",
        ["DashboardCancelRecommendationsEmpty"] = "Пока нет подписок, отмеченных как редко используемые.",
        ["DashboardCancellationReasonLowUsage"] = "Редко используется",
        ["SubscriptionNameRequired"] = "Название подписки обязательно.",
        ["AmountMustBePositive"] = "Сумма должна быть больше нуля.",
        ["MarkedPaidNote"] = "Отмечено как оплачено",
        ["PaymentSkippedNote"] = "Платеж пропущен",
        ["SubscriptionDisabledNote"] = "Подписка отключена",
        ["ValidationNameRequired"] = "Укажите название подписки.",
        ["ValidationCategoryRequired"] = "Выберите категорию.",
        ["ValidationAmountPositive"] = "Сумма должна быть больше нуля.",
        ["ValidationReminderNonNegative"] = "Напоминание не может быть отрицательным.",
        ["EditSubscriptionTitle"] = "Редактирование подписки",
        ["NewSubscriptionTitle"] = "Новая подписка",
        ["ValidateDataTitle"] = "Проверьте данные",
        ["SaveFailedTitle"] = "Не удалось сохранить",
        ["ExportCompletedMessage"] = "Excel-файл успешно сохранен.",
        ["ExportCompletedTitle"] = "Экспорт завершен",
        ["ExportErrorTitle"] = "Ошибка экспорта",
        ["ReminderNotificationTitle"] = "Ближайшие списания",
        ["ReminderMessageFormat"] = "Списание {0:N2} {1} запланировано на {2:d}",
        ["ReminderCheckIntervalFormat"] = "Раз в {0} минут",
        ["DataProfileText"] = "Без облака, данные остаются на этом компьютере.",
        ["LanguageRussian"] = "Русский",
        ["LanguageEnglish"] = "Английский",
        ["FilterAll"] = "Все",
        ["FilterAllCategories"] = "Все категории",
        ["FilterActive"] = "Активные",
        ["FilterDisabled"] = "Отключенные",
        ["FilterDueSoon"] = "Скоро спишутся",
        ["BillingCycleMonthly"] = "Каждый месяц",
        ["BillingCycleQuarterly"] = "Каждый квартал",
        ["BillingCycleSemiAnnual"] = "Раз в полгода",
        ["BillingCycleYearly"] = "Раз в год",
        ["Unknown"] = "Неизвестно",
        ["PaymentStatusPlanned"] = "Запланирован",
        ["PaymentStatusPaid"] = "Оплачен",
        ["PaymentStatusSkipped"] = "Пропущен",
        ["PaymentStatusCancelled"] = "Отменен",
        ["PaymentStatusFailed"] = "Ошибка",
        ["ExcelSheetSubscriptions"] = "Подписки",
        ["ExcelSheetHistory"] = "История",
        ["ExcelHeaderName"] = "Название",
        ["ExcelHeaderCategory"] = "Категория",
        ["ExcelHeaderAmount"] = "Сумма",
        ["ExcelHeaderCurrency"] = "Валюта",
        ["ExcelHeaderCycle"] = "Период",
        ["ExcelHeaderNextPayment"] = "Следующее списание",
        ["ExcelHeaderStatus"] = "Статус",
        ["ExcelHeaderDate"] = "Дата",
        ["ExcelHeaderSubscription"] = "Подписка",
        ["ExcelHeaderComment"] = "Комментарий",
        ["ExcelStatusActive"] = "Активна",
        ["ExcelStatusDisabled"] = "Отключена",
        ["ExcelFileDialogFilter"] = "Книга Excel (*.xlsx)|*.xlsx",
        ["BackupCreateButton"] = "Создать резервную копию",
        ["BackupRestoreButton"] = "Восстановить из копии",
        ["BackupFileDialogFilter"] = "SQLite backup (*.sqlite;*.db)|*.sqlite;*.db",
        ["BackupCreatedTitle"] = "Резервная копия создана",
        ["BackupCreatedMessage"] = "Резервная копия сохранена в:\n{0}",
        ["BackupFailedTitle"] = "Ошибка резервного копирования",
        ["BackupRestoreConfirmTitle"] = "Восстановление базы",
        ["BackupRestoreConfirmMessage"] = "Текущие данные будут заменены содержимым выбранной резервной копии. Продолжить?",
        ["BackupRestoredTitle"] = "База восстановлена",
        ["BackupRestoredMessage"] = "Резервная копия восстановлена. Приложение будет перезапущено.",
        ["DialogKindInfo"] = "Информация",
        ["DialogKindWarning"] = "Предупреждение",
        ["DialogKindError"] = "Ошибка",
        ["DialogKindConfirm"] = "Подтверждение",
        ["DialogOk"] = "ОК",
        ["DialogCancel"] = "Отмена",
        ["DialogDelete"] = "Удалить",
        ["DialogRestore"] = "Восстановить",
        ["DeleteSubscriptionConfirmTitle"] = "Удаление подписки",
        ["DeleteSubscriptionConfirmMessage"] = "Удалить подписку \"{0}\"? Это действие нельзя отменить.",
        ["ReminderToastMoreFormat"] = "И еще {0} платеж(а).",
        ["CategoryNameRequired"] = "Название категории обязательно.",
        ["CategoryColorInvalid"] = "Цвет категории должен быть в формате #RRGGBB.",
        ["CategoryDuplicateName"] = "Категория с таким названием уже существует.",
        ["CategoryNotFound"] = "Категория не найдена.",
        ["CategoryDeleteSystemError"] = "Системную категорию нельзя удалить.",
        ["CategoryTransferRequired"] = "Выберите категорию, в которую нужно перенести подписки.",
        ["CategoryTransferNotFound"] = "Категория для переноса не найдена.",
        ["CategorySaveFailedTitle"] = "Не удалось сохранить категорию",
        ["CategoryDeleteFailedTitle"] = "Не удалось удалить категорию",
        ["CategoryEditDialogTitle"] = "Редактирование категории",
        ["CategoryCreateDialogTitle"] = "Новая категория",
        ["CategoryDeleteDialogTitle"] = "Удаление категории",
        ["CategoryDeleteConfirmMessage"] = "Удалить категорию \"{0}\"?",
        ["CategoryDeleteTransferMessage"] = "Категория \"{0}\" используется в {1} подписк(ах). Выберите новую категорию для переноса перед удалением."
    };

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["DashboardNav"] = "Dashboard",
        ["SubscriptionsNav"] = "Subscriptions",
        ["CalendarNav"] = "Payment calendar",
        ["AnalyticsNav"] = "Analytics",
        ["HistoryNav"] = "Payment history",
        ["SettingsNav"] = "Settings",
        ["MainSubtitle"] = "Personal subscription control",
        ["HeaderBadgeText"] = "Local · SQLite · No cloud",
        ["SidebarStatusTitle"] = "Local mode",
        ["SidebarStatusDetails"] = "Database: SQLite",
        ["LastRefreshTodayFormat"] = "Last refresh: today, {0:HH:mm}",
        ["LastRefreshDateFormat"] = "Last refresh: {0:g}",
        ["ThemeDark"] = "Dark",
        ["ThemeLight"] = "Light",
        ["StorageMode"] = "SQLite, stored locally on this device",
        ["BackupStatus"] = "Backups let you save and restore the local database.",
        ["AppVersion"] = ".NET 8 · MVP build",
        ["NoComment"] = "No comment",
        ["NoUpcomingPayments"] = "No upcoming payments",
        ["AddFirstSubscription"] = "Add your first subscription",
        ["EmptyState"] = "Empty",
        ["PerMonthSuffix"] = "{0}/mo",
        ["NotCounted"] = "Excluded",
        ["StatusActive"] = "Active",
        ["StatusInactive"] = "Disabled",
        ["CountdownOverdue"] = "Overdue by {0} days",
        ["CountdownToday"] = "Today",
        ["CountdownInOneDay"] = "In 1 day",
        ["CountdownInFewDays"] = "In {0} days",
        ["CountdownInManyDays"] = "In {0} days",
        ["UrgencyOverdue"] = "Overdue",
        ["UrgencyToday"] = "Today",
        ["UrgencySoon"] = "Soon",
        ["UrgencyThisWeek"] = "This week",
        ["UrgencyPlanned"] = "Planned",
        ["MostExpensiveFallback"] = "—",
        ["DashboardCancelRecommendationsEmpty"] = "No subscriptions are marked as rarely used yet.",
        ["DashboardCancellationReasonLowUsage"] = "Rarely used",
        ["SubscriptionNameRequired"] = "Subscription name is required.",
        ["AmountMustBePositive"] = "Amount must be greater than zero.",
        ["MarkedPaidNote"] = "Marked as paid",
        ["PaymentSkippedNote"] = "Payment skipped",
        ["SubscriptionDisabledNote"] = "Subscription disabled",
        ["ValidationNameRequired"] = "Enter a subscription name.",
        ["ValidationCategoryRequired"] = "Select a category.",
        ["ValidationAmountPositive"] = "Amount must be greater than zero.",
        ["ValidationReminderNonNegative"] = "Reminder cannot be negative.",
        ["EditSubscriptionTitle"] = "Edit subscription",
        ["NewSubscriptionTitle"] = "New subscription",
        ["ValidateDataTitle"] = "Check your data",
        ["SaveFailedTitle"] = "Unable to save",
        ["ExportCompletedMessage"] = "The Excel file has been saved.",
        ["ExportCompletedTitle"] = "Export completed",
        ["ExportErrorTitle"] = "Export error",
        ["ReminderNotificationTitle"] = "Upcoming payments",
        ["ReminderMessageFormat"] = "A charge of {0:N2} {1} is scheduled for {2:d}",
        ["ReminderCheckIntervalFormat"] = "Every {0} minutes",
        ["DataProfileText"] = "No cloud sync, data stays on this computer.",
        ["LanguageRussian"] = "Russian",
        ["LanguageEnglish"] = "English",
        ["FilterAll"] = "All",
        ["FilterAllCategories"] = "All categories",
        ["FilterActive"] = "Active",
        ["FilterDisabled"] = "Disabled",
        ["FilterDueSoon"] = "Due soon",
        ["BillingCycleMonthly"] = "Every month",
        ["BillingCycleQuarterly"] = "Every quarter",
        ["BillingCycleSemiAnnual"] = "Every half-year",
        ["BillingCycleYearly"] = "Every year",
        ["Unknown"] = "Unknown",
        ["PaymentStatusPlanned"] = "Planned",
        ["PaymentStatusPaid"] = "Paid",
        ["PaymentStatusSkipped"] = "Skipped",
        ["PaymentStatusCancelled"] = "Cancelled",
        ["PaymentStatusFailed"] = "Failed",
        ["ExcelSheetSubscriptions"] = "Subscriptions",
        ["ExcelSheetHistory"] = "History",
        ["ExcelHeaderName"] = "Name",
        ["ExcelHeaderCategory"] = "Category",
        ["ExcelHeaderAmount"] = "Amount",
        ["ExcelHeaderCurrency"] = "Currency",
        ["ExcelHeaderCycle"] = "Cycle",
        ["ExcelHeaderNextPayment"] = "Next payment",
        ["ExcelHeaderStatus"] = "Status",
        ["ExcelHeaderDate"] = "Date",
        ["ExcelHeaderSubscription"] = "Subscription",
        ["ExcelHeaderComment"] = "Comment",
        ["ExcelStatusActive"] = "Active",
        ["ExcelStatusDisabled"] = "Disabled",
        ["ExcelFileDialogFilter"] = "Excel workbook (*.xlsx)|*.xlsx",
        ["BackupCreateButton"] = "Create backup",
        ["BackupRestoreButton"] = "Restore backup",
        ["BackupFileDialogFilter"] = "SQLite backup (*.sqlite;*.db)|*.sqlite;*.db",
        ["BackupCreatedTitle"] = "Backup created",
        ["BackupCreatedMessage"] = "Backup saved to:\n{0}",
        ["BackupFailedTitle"] = "Backup error",
        ["BackupRestoreConfirmTitle"] = "Restore database",
        ["BackupRestoreConfirmMessage"] = "Current data will be replaced with the selected backup. Continue?",
        ["BackupRestoredTitle"] = "Database restored",
        ["BackupRestoredMessage"] = "Backup restored successfully. The application will restart now.",
        ["DialogKindInfo"] = "Information",
        ["DialogKindWarning"] = "Warning",
        ["DialogKindError"] = "Error",
        ["DialogKindConfirm"] = "Confirmation",
        ["DialogOk"] = "OK",
        ["DialogCancel"] = "Cancel",
        ["DialogDelete"] = "Delete",
        ["DialogRestore"] = "Restore",
        ["DeleteSubscriptionConfirmTitle"] = "Delete subscription",
        ["DeleteSubscriptionConfirmMessage"] = "Delete \"{0}\"? This action cannot be undone.",
        ["ReminderToastMoreFormat"] = "And {0} more payment(s).",
        ["CategoryNameRequired"] = "Category name is required.",
        ["CategoryColorInvalid"] = "Category color must use the #RRGGBB format.",
        ["CategoryDuplicateName"] = "A category with this name already exists.",
        ["CategoryNotFound"] = "Category was not found.",
        ["CategoryDeleteSystemError"] = "System categories cannot be deleted.",
        ["CategoryTransferRequired"] = "Choose a category to transfer subscriptions to.",
        ["CategoryTransferNotFound"] = "Transfer category was not found.",
        ["CategorySaveFailedTitle"] = "Unable to save category",
        ["CategoryDeleteFailedTitle"] = "Unable to delete category",
        ["CategoryEditDialogTitle"] = "Edit category",
        ["CategoryCreateDialogTitle"] = "New category",
        ["CategoryDeleteDialogTitle"] = "Delete category",
        ["CategoryDeleteConfirmMessage"] = "Delete category \"{0}\"?",
        ["CategoryDeleteTransferMessage"] = "Category \"{0}\" is used by {1} subscription(s). Choose a new category to move them before deletion."
    };

    private static string _currentLanguageCode = "ru-RU";

    public static string CurrentLanguageCode => _currentLanguageCode;

    public static string NormalizeLanguageCode(string? languageCode)
    {
        return string.Equals(languageCode, "en", StringComparison.OrdinalIgnoreCase)
            || string.Equals(languageCode, "en-US", StringComparison.OrdinalIgnoreCase)
            ? "en-US"
            : "ru-RU";
    }

    public static void SetLanguage(string? languageCode)
    {
        _currentLanguageCode = NormalizeLanguageCode(languageCode);
    }

    public static string Get(string key)
    {
        var dictionary = _currentLanguageCode == "en-US" ? En : Ru;
        if (dictionary.TryGetValue(key, out var value))
        {
            return value;
        }

        return Ru.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, Get(key), args);
    }
}
